### ISSUE TITLE
Example not working since v1.0.1

### ISSUE THREAD

**Issue by TheJKM** [security-union/yew-websocket#10]
Due to removal of macros, the example is unable to compile with latest version v1.0.1. Would be cool if you could update the example to be compatible with the latest version.

**Comment by darioalessandro** [comment]
roger that, I am on it.

**Comment by darioalessandro** [comment]
It is done 😄 thank you for bringing this to my attention.

**Comment by barafael** [comment]
Is including the macro from pre-1.0 the way to go here also for our own projects?

**Comment by darioalessandro** [comment]
You can do that or use: https://github.com/security-union/videocall-rs/blob/b578878b3967a20d9f9fe1e959664c42b2f75b45/yew-ui/src/components/attendants.rs#L304-L320 makes sense @barafael ?

**Comment by barafael** [comment]
Sure, thanks!
