### ISSUE TITLE
Support for Yew 0.21.0

### ISSUE THREAD

**Issue by Maurdekye** [security-union/yew-websocket#12]
Is this project dead?

**Comment by darioalessandro** [comment]
Negative 😄 we do not submit too many PRs because it does the thing, let me go ahead and upgrade it to support 0.21.0 would be nice if stupid yew wouldn't break compatibility every time they update.

**Comment by LucaCappelletti94** [comment]
I mean, isn't it best practice to nullify all previous documentation at each damn release?

I am trying to write an example using Actix backend sockets and Yew frontend sockets, do you have any example of use of this crate with any backend?

**Comment by LucaCappelletti94** [comment]
This issue should be now closed since it was handled in pull request https://github.com/security-union/yew-websocket/pull/13

**Comment by darioalessandro** [comment]
sweet lets gooo!

**Comment by darioalessandro** [comment]
Here's the latest version: https://crates.io/crates/yew-websocket

```
yew-websocket = "1.21.0"
```
