### ISSUE TITLE
Compatibility with Yew v0.19.3

### ISSUE THREAD

**Issue by hanusek** [security-union/yew-websocket#3]
Hello @darioalessandro 
I have a problem with your example and yew 0.19.3.

```
error[E0308]: arguments to this function are incorrect
   --> examples/counter/src/main.rs:123:32
    |
123 |                     let task = WebSocketService::connect(
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: expected enum `yew::callback::Callback`, found enum `yew::Callback`
   --> examples/counter/src/main.rs:125:25
    |
125 |                         callback,
    |                         ^^^^^^^^
    = note: enum `yew::Callback` and enum `yew::callback::Callback` have similar names, but are actually distinct types
note: enum `yew::Callback` is defined in crate `yew`
   --> /home/mhanusek/work/code/rnd/yew/packages/yew/src/callback.rs:19:1
```

**Comment by darioalessandro** [comment]
Hey @hanusek !! Thanks for bringing this up, I'll take a look by Dec 26 eod. Happy holidays 😄

**Comment by darioalessandro** [comment]
I did not forget about this, give me until eod today eastern time.

**Comment by finga** [comment]
Is this project still ongoing/maintained and will it be compatible with yew v0.20? Maybe it makes sense to add this information to the readme?

**Comment by darioalessandro** [comment]
It will be, life got complex but it will be compatible soon

**Comment by darioalessandro** [comment]
@griffobeid haaaaalp

**Comment by griffobeid** [comment]
Yeah I can help with this

**Comment by darioalessandro** [comment]
Thank you brother I am swamped with May Mobility stuff 🌊🌊🌊

**Comment by griffobeid** [comment]
@hanusek Could I get some more details on how to reproduce this? Running the example in this repository works for me. 
- What rust version are you using?
- Can you send the `Cargo.toml` and `main.rs`?

**Comment by darioalessandro** [comment]
I think that to reproduce you would have to bump yew to 19.3 and see if it still compiles

**Comment by darioalessandro** [comment]
I agree with griffin. 

yew-websocket does work with 0.19.3 

1. clone repo
2. go to examples/websocket-demo
3. run `trunk serve`
4. open localhost:8080 and test that you can interact with the websocket server.

**Comment by griffobeid** [comment]
In regards to supporting yew v0.20. Do we want maintain backwards compatibility with yew v0.19 still?

**Comment by darioalessandro** [comment]
Imo we should break compat

**Comment by finga** [comment]
Any update on this?

**Comment by darioalessandro** [comment]
Yes, version 0.20.0 is supported now!! https://crates.io/crates/yew-websocket

**Comment by darioalessandro** [comment]
@finga solved in https://github.com/security-union/yew-websocket/pull/4 thanks for reporting!!!
